// flow-typed signature: 80476557e1b1be866a59095b126a7856
// flow-typed version: <<STUB>>/curry_v^1.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'curry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'curry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'curry/curry' {
  declare module.exports: any;
}

declare module 'curry/curry.min' {
  declare module.exports: any;
}

declare module 'curry/examples/usage' {
  declare module.exports: any;
}

declare module 'curry/test/curry-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'curry/curry.js' {
  declare module.exports: $Exports<'curry/curry'>;
}
declare module 'curry/curry.min.js' {
  declare module.exports: $Exports<'curry/curry.min'>;
}
declare module 'curry/examples/usage.js' {
  declare module.exports: $Exports<'curry/examples/usage'>;
}
declare module 'curry/test/curry-test.js' {
  declare module.exports: $Exports<'curry/test/curry-test'>;
}
